permissions:
  contents: write
name: Update M3U

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script
        run: python update_m3u.py

      - name: Commit y push
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "update stream" || echo "no changes"
          git push
